[project]
name = "spending-app-telegram-bot"
version = "2025.4.18"
requires-python = ">=3.10"
dependencies = [
    "aiosqlite>=0.21.0",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "pydantic>=2.11.3",
    "python-dotenv>=1.1.0",
    "python-telegram-bot>=22.0",
    "requests>=2.32.3",
]
