[project]
name = "spending-app-telegram-bot"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "pydantic>=2.11.3",
    "python-dotenv>=1.1.0",
    "python-telegram-bot>=22.0",
]
